sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alias:
    endpoint: oss-cn-wuhan-lr.aliyuncs.com
    access-key-id: ${ALI_OSS_ACCESS_KEY_ID}
    access-key-secret: ${ALI_OSS_ACCESS_KEY_SECRET}
    bucket-name: sky-gc
